## Introduction

In [1]:
# impor libraries
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [14]:
# creating a numpy array
a = np.array([1,2,3,4,5])
# printing 
a

array([1, 2, 3, 4, 5])

In [9]:
# checking the type of the array
type(a)

numpy.ndarray

In [10]:
# checking the shape of the array
a.shape

(5,)

In [12]:
# 0 dimensional array
a = np.array(2)
a, a.shape, a.ndim

(array(2), (), 0)

In [15]:
# 1 dimensonal array
a = np.array([1,2,3,4,5])
a, a.shape, a.ndim

(array([1, 2, 3, 4, 5]), (5,), 1)

In [16]:
# 2 dimensonal array
a = np.array([[1,2,3],[4,5,6]])
a, a.shape, a.ndim

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3),
 2)

In [17]:
# 3 dimensonal array (list/vector of 2d list/vector)
a = np.array([[[1,2,3],[4,5,6]],
              [[7,8,9],[10,11,12]]])
a, a.shape, a.ndim

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 (2, 2, 3),
 3)

## Array Indexing and Slicing

In [20]:
a = np.array([1,3,4,5,8])
a[0] # first element
a[-1] # last element 

8

In [23]:
a = np.array([[1,3,4,5,8],
              [1,3,4,5,8]])
a[0,0] # first element of the first row
a[1,4] # last element of the second row

8

In [27]:
a = np.array([[[1, 2, 3, 4],[11, 22, 33, 44]],
              [[10, 20, 30, 40],[100, 200, 300, 400]]])
a, a.ndim

(array([[[  1,   2,   3,   4],
         [ 11,  22,  33,  44]],
 
        [[ 10,  20,  30,  40],
         [100, 200, 300, 400]]]),
 3)

In [33]:
a[0][1][2]
a[1][0][3]

40

In [34]:
a[1, :, 2]

array([ 30, 300])

## Data Types

In [ ]:
a = np.array([1,4,5,3,7,8])
a.dtype # data type of the array

dtype('int64')

In [ ]:
a = np.array(['apple', 'bananas'])
a.dtype 

dtype('<U7')

In [38]:
a = np.array(['apple', 'bananas'], dtype='S')
a

array([b'apple', b'bananas'], dtype='|S7')

In [39]:
a = np.array(['0.0', '1.1'], dtype='f')
a, a.dtype

(array([0. , 1.1], dtype=float32), dtype('float32'))

In [42]:
a = np.array([1,22, 341, 12, 42])
a.sort() # short the array
a

array([  1,  12,  22,  42, 341])

In [ ]:
-np.sort(-a) 

array([341,  42,  22,  12,   1])

## `np.nan` and `np.inf`  

In [49]:
np.nan == np.nan # return boolen value
a = np.nan
b = np.nan
a , b

(nan, nan)

In [50]:
# np.nan values are not equal to themselves or any other value.
a==b, a>b, a<b

(False, False, False)

In [52]:
# np.inf can be used to represent upper bounds or extremes in optimization problems, comparisons, or iterative calculations.
a = np.inf
b = np.inf
a,b

(inf, inf)

In [54]:
a==b, a>b # np.inf is equal to itself but not to any other values.

(True, False)

In [55]:
a = np.array([[1,2,3], [4,5,6]], dtype='float')
a.shape, a.dtype

((2, 3), dtype('float64'))

In [56]:
a[0][1] = np.nan
a[0][2] = np.inf

In [57]:
a

array([[ 1., nan, inf],
       [ 4.,  5.,  6.]])

## Statistical Operations

In [61]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [62]:
a.mean(), np.mean(a), np.mean([1, 2, 3, 4, 5, 6, 7]) # mean of the array

(4.0, 4.0, 4.0)

In [63]:
a.var(), a.std(), np.median(a)

(4.0, 2.0, 4.0)

In [64]:
a = np.array([[1,2,3,4,5,6,7], [11,22,33,44,55,66,77]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [11, 22, 33, 44, 55, 66, 77]])

In [65]:
a.mean(), np.mean(a), np.median(a), a.var(), a.std()

(24.0, 24.0, 9.0, 644.0, 25.37715508089904)

## Shape(), Reshape(), Ravel(), Flatten()

In [66]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [11, 22, 33, 44, 55, 66, 77]])

In [ ]:
a.ndim, a.shape # 2d array with 2 rows and 7 columns

(2, (2, 7))

In [ ]:
a = a.reshape(1, -1) # reshaping the array to 1 row and 14 columns
a

array([[ 1,  2,  3,  4,  5,  6,  7, 11, 22, 33, 44, 55, 66, 77]])

In [71]:
a.ndim, a.shape # 2d array with 1 row and 14 columns

(2, (1, 14))

In [72]:
a = np.array([[1,2,3,4,5,6,7], [11,22,33,44,55,66,77]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [11, 22, 33, 44, 55, 66, 77]])

ravel(): Returns a flattened view of the array (if possible). If a view cannot be created, it returns a copy. It is memory-efficient and reflects changes made to the original array if a view is used.

flatten(): Always returns a flattened copy of the array. Changes to the resulting array do not affect the original array.

Use ravel() when performance and memory efficiency matter, and flatten() when you need an independent copy.

In [73]:
a.ravel() # convert the 2d array to 1d array

array([ 1,  2,  3,  4,  5,  6,  7, 11, 22, 33, 44, 55, 66, 77])

In [ ]:
a.flatten() # convert the 2d array to 1d array



array([ 1,  2,  3,  4,  5,  6,  7, 11, 22, 33, 44, 55, 66, 77])

## arange(), linspace(), range(), random(), zeros(), and ones() 


In [75]:
np.arange(1, 11, dtype='int') # create an array of numbers from 1 to 10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
np.arange(1, 11, 3) # create an array of numbers from 1 to 10 with a step of 3

array([ 1,  4,  7, 10])

In [77]:
np.linspace(1, 10, 4) # create an array of 4 numbers from 1 to 10

array([ 1.,  4.,  7., 10.])

In [ ]:
from numpy import random # import the random module from numpy

In [79]:
random.randint(1, 10, 5) # generate 5 random numbers between 1 and 10

array([4, 7, 2, 1, 2])

In [ ]:
np.array(range(1, 10)) 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
np.zeros((2, 3)) # create a 2x3 array of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones([5, 5, 4]).shape # create a 5x5x4 array of ones

(5, 5, 4)

In [84]:
np.tile([1,2,3], 3) # repeat the array 3 times

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [86]:
np.repeat([1,2,3], 2) # repeat each element of the array 2 times

array([1, 1, 2, 2, 3, 3])

## Where

In [87]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [11, 22, 33, 44, 55, 66, 77]])

In [88]:
index = np.where(a < 10) # get the index of elements less than 10
index

(array([0, 0, 0, 0, 0, 0, 0]), array([0, 1, 2, 3, 4, 5, 6]))

In [89]:
b = a[index] 
b

array([1, 2, 3, 4, 5, 6, 7])

In [90]:
index = np.where(b>5)
b[index]

array([6, 7])

In [91]:
a.argmax() # get the index of the maximum value in the array

13

In [92]:
a.flatten()[13] # get the maximum value in the array

77

In [93]:
a.argmin() # get the index of the minimum value in the array

0